# Generated by Django 4.2.6 on 2023-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_property_photos_propertyphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
