# Generated by Django 4.2.6 on 2024-01-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_propertyphoto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
