# Generated by Django 4.2.6 on 2024-01-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
