# Generated by Django 4.2.6 on 2024-01-04 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
