# Generated by Django 4.2.6 on 2024-01-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_property_rented_to_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
