# Generated by Django 4.2.6 on 2024-01-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rating_user'),
        ('base', '0007_property_is_active_rentalrequest_is_active'),
    ]

    operations = [
    ]
