# Generated by Django 4.2.6 on 2024-01-09 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_merge_20240106_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rented_to',
        ),
        migrations.AddField(
            model_name='property',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='base.property'),
        ),
    ]
