# Generated by Django 4.2.6 on 2024-01-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_property_status'),
        ('base', '0008_merge_20240106_0459'),
    ]

    operations = [
    ]
