# Generated by Django 4.2.6 on 2024-01-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_0007_property_status_0008_merge_20240106_0459'),
        ('base', '0010_alter_rating_property_alter_rating_user'),
    ]

    operations = [
    ]
